// Weapon profiles for all factions
const weaponProfiles = {
	// Space Marines
	"bolt-rifle": {
		name: "Bolt Rifle",
		range: 24,
		attacks: 2,
		bs: 3,
		strength: 4,
		ap: 1,
		damage: 1,
		abilities: [],
	},
	"bolt-pistol": {
		name: "Bolt Pistol",
		range: 12,
		attacks: 1,
		bs: 3,
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: ["Pistol"],
	},
	"storm-bolter": {
		name: "Storm Bolter",
		range: 24,
		attacks: 2,
		bs: 3,
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: ["Rapid Fire 2"],
	},
	"power-fist": {
		name: "Power Fist",
		range: "Melee",
		attacks: 2,
		ws: 3,
		strength: 8,
		ap: 2,
		damage: 2,
		abilities: ["-1 to Hit"],
	},
	"plasma-incinerator": {
		name: "Plasma Incinerator",
		range: 24,
		attacks: 2,
		bs: 3,
		strength: 7,
		ap: 2,
		damage: 2,
		abilities: ["Rapid Fire 1"],
	},
	// Astra Militarum
	lasgun: {
		name: "Lasgun",
		range: 24,
		attacks: 1,
		bs: 4,
		strength: 3,
		ap: 0,
		damage: 1,
		abilities: ["Rapid Fire 1"],
	},
	laspistol: {
		name: "Laspistol",
		range: 12,
		attacks: 1,
		bs: 4,
		strength: 3,
		ap: 0,
		damage: 1,
		abilities: ["Pistol"],
	},
	"plasma-gun": {
		name: "Plasma Gun",
		range: 24,
		attacks: 1,
		bs: 4,
		strength: 7,
		ap: 2,
		damage: 1,
		abilities: ["Rapid Fire 1"],
	},
	"battle-cannon": {
		name: "Battle Cannon",
		range: 48,
		attacks: "D6+3",
		bs: 4,
		strength: 10,
		ap: 2,
		damage: 3,
		abilities: ["Blast"],
	},
	// Adepta Sororitas
	bolter: {
		name: "Bolter",
		range: 24,
		attacks: 1,
		bs: 3,
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: ["Rapid Fire 1"],
	},
	"storm-bolter-sororitas": {
		name: "Storm Bolter",
		range: 24,
		attacks: 2,
		bs: 3,
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: ["Rapid Fire 2"],
	},
	flamer: {
		name: "Flamer",
		range: 12,
		attacks: "D6",
		bs: "-",
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: ["Ignores Cover", "Auto Hits"],
	},
	// Adeptus Custodes
	"guardian-spear": {
		name: "Guardian Spear",
		range: 24,
		attacks: 2,
		bs: 2,
		strength: 4,
		ap: 1,
		damage: 2,
		abilities: [],
	},
	"sentinel-blade": {
		name: "Sentinel Blade",
		range: "Melee",
		attacks: 3,
		ws: 2,
		strength: 5,
		ap: 3,
		damage: 2,
		abilities: [],
	},
	// Chaos Space Marines
	"chaos-boltgun": {
		name: "Boltgun",
		range: 24,
		attacks: 1,
		bs: 3,
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: ["Rapid Fire 1"],
	},
	chainsword: {
		name: "Chainsword",
		range: "Melee",
		attacks: 1,
		ws: 3,
		strength: "User",
		ap: 0,
		damage: 1,
		abilities: ["Extra Attack"],
	},
	// Death Guard
	"plague-bolter": {
		name: "Plague Bolter",
		range: 24,
		attacks: 2,
		bs: 3,
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: ["Rapid Fire 1", "Plague Weapon"],
	},
	"plague-knife": {
		name: "Plague Knife",
		range: "Melee",
		attacks: 1,
		ws: 3,
		strength: "User",
		ap: 0,
		damage: 1,
		abilities: ["Plague Weapon"],
	},
	// Thousand Sons
	"inferno-boltgun": {
		name: "Inferno Boltgun",
		range: 24,
		attacks: 1,
		bs: 3,
		strength: 4,
		ap: 2,
		damage: 1,
		abilities: ["Rapid Fire 1"],
	},
	"force-stave": {
		name: "Force Stave",
		range: "Melee",
		attacks: 2,
		ws: 3,
		strength: 6,
		ap: 1,
		damage: 2,
		abilities: ["Psychic"],
	},
	// Orks
	shoota: {
		name: "Shoota",
		range: 18,
		attacks: 2,
		bs: 5,
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: ["Dakka! Dakka!"],
	},
	slugga: {
		name: "Slugga",
		range: 12,
		attacks: 1,
		bs: 5,
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: ["Pistol"],
	},
	choppa: {
		name: "Choppa",
		range: "Melee",
		attacks: 1,
		ws: 3,
		strength: "User",
		ap: 1,
		damage: 1,
		abilities: [],
	},
	// T'au Empire
	"pulse-rifle": {
		name: "Pulse Rifle",
		range: 30,
		attacks: 1,
		bs: 4,
		strength: 5,
		ap: 0,
		damage: 1,
		abilities: ["Rapid Fire 1"],
	},
	"pulse-carbine": {
		name: "Pulse Carbine",
		range: 18,
		attacks: 2,
		bs: 4,
		strength: 5,
		ap: 0,
		damage: 1,
		abilities: ["Assault"],
	},
	"fusion-blaster": {
		name: "Fusion Blaster",
		range: 18,
		attacks: 1,
		bs: 4,
		strength: 9,
		ap: 4,
		damage: "D6",
		abilities: ["Melta 2"],
	},
	// Necrons
	"gauss-flayer": {
		name: "Gauss Flayer",
		range: 24,
		attacks: 1,
		bs: 3,
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: ["Rapid Fire 1", "Lethal Hits"],
	},
	"gauss-reaper": {
		name: "Gauss Reaper",
		range: 12,
		attacks: 2,
		bs: 3,
		strength: 5,
		ap: 1,
		damage: 1,
		abilities: ["Lethal Hits"],
	},
	"hyperphase-sword": {
		name: "Hyperphase Sword",
		range: "Melee",
		attacks: 2,
		ws: 3,
		strength: 6,
		ap: 3,
		damage: 2,
		abilities: [],
	},
	// Aeldari
	"shuriken-catapult": {
		name: "Shuriken Catapult",
		range: 18,
		attacks: 2,
		bs: 3,
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: ["Shuriken"],
	},
	"shuriken-pistol": {
		name: "Shuriken Pistol",
		range: 12,
		attacks: 1,
		bs: 3,
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: ["Pistol", "Shuriken"],
	},
	"power-sword-eldar": {
		name: "Power Sword",
		range: "Melee",
		attacks: 2,
		ws: 3,
		strength: 4,
		ap: 3,
		damage: 1,
		abilities: [],
	},
	// Drukhari
	"splinter-rifle": {
		name: "Splinter Rifle",
		range: 24,
		attacks: 2,
		bs: 3,
		strength: 3,
		ap: 0,
		damage: 1,
		abilities: ["Poisoned"],
	},
	agoniser: {
		name: "Agoniser",
		range: "Melee",
		attacks: 2,
		ws: 3,
		strength: 4,
		ap: 2,
		damage: 1,
		abilities: ["Poisoned"],
	},
	// Tyranids
	fleshborer: {
		name: "Fleshborer",
		range: 18,
		attacks: 1,
		bs: 4,
		strength: 5,
		ap: 0,
		damage: 1,
		abilities: ["Assault"],
	},
	devourer: {
		name: "Devourer",
		range: 18,
		attacks: 2,
		bs: 4,
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: [],
	},
	"scything-talons": {
		name: "Scything Talons",
		range: "Melee",
		attacks: 2,
		ws: 3,
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: ["Re-roll Hit rolls of 1"],
	},
	// Genestealer Cults
	autopistol: {
		name: "Autopistol",
		range: 12,
		attacks: 1,
		bs: 4,
		strength: 3,
		ap: 0,
		damage: 1,
		abilities: ["Pistol"],
	},
	"cultist-knife": {
		name: "Cultist Knife",
		range: "Melee",
		attacks: 1,
		ws: 4,
		strength: 3,
		ap: 0,
		damage: 1,
		abilities: [],
	},
	// 10th Edition Weapon Profiles
	boltgun: {
		name: "Boltgun",
		range: 24,
		attacks: 1,
		bs: 3,
		strength: 4,
		ap: 0,
		damage: 1,
		abilities: ["Rapid Fire 1"],
	},
	"power-sword": {
		name: "Power Sword",
		range: "Melee",
		attacks: 2,
		ws: 3,
		strength: 5,
		ap: 3,
		damage: 1,
		abilities: [],
	},
	"plasma-cutter": {
		name: "Plasma Cutter",
		range: 12,
		attacks: 1,
		bs: 3,
		strength: 8,
		ap: 3,
		damage: 2,
		abilities: ["Pistol", "Hazardous"],
	},
	"onslaught-gatling-cannon": {
		name: "Onslaught Gatling Cannon",
		range: 30,
		attacks: 8,
		bs: 3,
		strength: 6,
		ap: 1,
		damage: 1,
		abilities: ["Sustained Hits 1"],
	},
	fist: {
		name: "Dreadnought Combat Fist",
		range: "Melee",
		attacks: 4,
		ws: 3,
		strength: 12,
		ap: 3,
		damage: 3,
		abilities: ["-1 to Hit"],
	},
	"heavy-bolter": {
		name: "Heavy Bolter",
		range: 36,
		attacks: 3,
		bs: 4,
		strength: 5,
		ap: 1,
		damage: 2,
		abilities: ["Sustained Hits 1"],
	},
	"las-talon": {
		name: "Las-talon",
		range: 24,
		attacks: 2,
		bs: 3,
		strength: 12,
		ap: 3,
		damage: "D6+1",
		abilities: [],
	},
	"twin-lascannon": {
		name: "Twin Lascannon",
		range: 48,
		attacks: 2,
		bs: 3,
		strength: 12,
		ap: 3,
		damage: "D6+1",
		abilities: [],
	},
	"melta-rifle": {
		name: "Melta Rifle",
		range: 18,
		attacks: 1,
		bs: 3,
		strength: 9,
		ap: 4,
		damage: "D6",
		abilities: ["Melta 2"],
	},
	"hot-shot-lasgun": {
		name: "Hot-shot Lasgun",
		range: 18,
		attacks: 1,
		bs: 4,
		strength: 4,
		ap: 2,
		damage: 1,
		abilities: ["Rapid Fire 1"],
	},
	meltagun: {
		name: "Meltagun",
		range: 12,
		attacks: 1,
		bs: 4,
		strength: 9,
		ap: 4,
		damage: "D6",
		abilities: ["Melta 2"],
	},
	"ripper-gun": {
		name: "Ripper Gun",
		range: 12,
		attacks: 3,
		bs: 4,
		strength: 5,
		ap: 1,
		damage: 2,
		abilities: ["Assault"],
	},
	"multi-laser": {
		name: "Multi-laser",
		range: 36,
		attacks: 3,
		bs: 4,
		strength: 6,
		ap: 0,
		damage: 1,
		abilities: [],
	},
	// Tyranid weapons
	"monstrous-bonesword": {
		name: "Monstrous Bonesword",
		range: "Melee",
		attacks: 4,
		ws: 3,
		strength: 9,
		ap: 2,
		damage: 2,
		abilities: [],
	},
	"venom-cannon": {
		name: "Venom Cannon",
		range: 36,
		attacks: 3,
		bs: 4,
		strength: 8,
		ap: 2,
		damage: 2,
		abilities: ["Blast"],
	},
	"monstrous-scything-talons": {
		name: "Monstrous Scything Talons",
		range: "Melee",
		attacks: 4,
		ws: 3,
		strength: 8,
		ap: 1,
		damage: 2,
		abilities: ["Re-roll Hit rolls of 1"],
	},
	"impaler-cannon": {
		name: "Impaler Cannon",
		range: 36,
		attacks: 2,
		bs: 4,
		strength: 10,
		ap: 2,
		damage: 3,
		abilities: [],
	},
	"warp-blast": {
		name: "Warp Blast",
		range: 18,
		attacks: "D3",
		bs: 3,
		strength: 9,
		ap: 3,
		damage: 3,
		abilities: ["Psychic"],
	},
	"rending-claws": {
		name: "Rending Claws",
		range: "Melee",
		attacks: 3,
		ws: 3,
		strength: 4,
		ap: 1,
		damage: 1,
		abilities: ["Rending"],
	},
	// Add more weapons for each faction as needed
};

// Unit profiles for all factions
const unitDatabase = {
	"space-marines": [
		{
			name: "Intercessor Squad",
			wounds: 2,
			models: 10,
			save: 3,
			leadership: 6,
			oc: 2,
			movement: 6,
			toughness: 4,
			role: "Battleline",
			weapons: ["bolt-rifle", "bolt-pistol"],
			invulnSave: null,
		},
		{
			name: "Assault Intercessors",
			wounds: 2,
			models: 10,
			save: 3,
			leadership: 6,
			oc: 2,
			movement: 6,
			toughness: 4,
			role: "Battleline",
			weapons: ["bolt-pistol", "chainsword"],
			invulnSave: null,
		},
		{
			name: "Heavy Intercessors",
			wounds: 3,
			models: 5,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 5,
			toughness: 6,
			role: "Battleline",
			weapons: ["bolt-rifle", "bolt-pistol"],
			invulnSave: null,
		},
		{
			name: "Infiltrators",
			wounds: 2,
			models: 5,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Battleline",
			weapons: ["bolt-pistol", "bolt-rifle"],
			invulnSave: null,
		},
		{
			name: "Incursors",
			wounds: 2,
			models: 5,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Battleline",
			weapons: ["bolt-pistol", "bolt-rifle"],
			invulnSave: null,
		},
		{
			name: "Tactical Squad",
			wounds: 1,
			models: 10,
			save: 3,
			leadership: 6,
			oc: 2,
			movement: 6,
			toughness: 4,
			role: "Battleline",
			weapons: ["boltgun", "bolt-pistol"],
			invulnSave: null,
		},
		{
			name: "Scout Squad",
			wounds: 1,
			models: 5,
			save: 4,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Battleline",
			weapons: ["bolt-pistol", "boltgun"],
			invulnSave: null,
		},
		{
			name: "Terminator Squad",
			wounds: 3,
			models: 5,
			save: 2,
			leadership: 6,
			oc: 1,
			movement: 5,
			toughness: 5,
			role: "Elite",
			weapons: ["storm-bolter", "power-fist"],
			invulnSave: 5,
		},
		{
			name: "Aggressors",
			wounds: 3,
			models: 3,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 5,
			toughness: 6,
			role: "Elite",
			weapons: ["bolt-pistol", "power-fist"],
			invulnSave: null,
		},
		{
			name: "Bladeguard Veterans",
			wounds: 3,
			models: 3,
			save: 2,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 5,
			role: "Elite",
			weapons: ["bolt-pistol", "power-sword"],
			invulnSave: 4,
		},
		{
			name: "Company Veterans",
			wounds: 2,
			models: 5,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Elite",
			weapons: ["bolt-pistol", "boltgun"],
			invulnSave: null,
		},
		{
			name: "Apothecary",
			wounds: 5,
			models: 1,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Character",
			weapons: ["bolt-pistol"],
			invulnSave: null,
		},
		{
			name: "Ancient",
			wounds: 5,
			models: 1,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Character",
			weapons: ["bolt-pistol"],
			invulnSave: null,
		},
		{
			name: "Captain",
			wounds: 5,
			models: 1,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Character",
			weapons: ["bolt-pistol", "power-fist"],
			invulnSave: 4,
		},
		{
			name: "Librarian",
			wounds: 5,
			models: 1,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Character",
			weapons: ["bolt-pistol", "power-sword"],
			invulnSave: 4,
		},
		{
			name: "Lieutenant",
			wounds: 5,
			models: 1,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Character",
			weapons: ["bolt-pistol", "power-sword"],
			invulnSave: null,
		},
		{
			name: "Techmarine",
			wounds: 5,
			models: 1,
			save: 2,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Character",
			weapons: ["bolt-pistol", "plasma-cutter"],
			invulnSave: null,
		},
		{
			name: "Chaplain",
			wounds: 5,
			models: 1,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Character",
			weapons: ["bolt-pistol"],
			invulnSave: 4,
		},
		{
			name: "Redemptor Dreadnought",
			wounds: 13,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 3,
			movement: 8,
			toughness: 10,
			role: "Vehicle",
			weapons: ["plasma-incinerator", "onslaught-gatling-cannon", "fist"],
			invulnSave: null,
		},
		{
			name: "Repulsor",
			wounds: 16,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 5,
			movement: 10,
			toughness: 10,
			role: "Vehicle",
			weapons: ["heavy-bolter", "las-talon", "storm-bolter"],
			invulnSave: null,
		},
		{
			name: "Land Raider",
			wounds: 16,
			models: 1,
			save: 2,
			leadership: 7,
			oc: 5,
			movement: 10,
			toughness: 12,
			role: "Vehicle",
			weapons: ["twin-lascannon", "heavy-bolter", "storm-bolter"],
			invulnSave: null,
		},
		{
			name: "Outriders",
			wounds: 4,
			models: 3,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 14,
			toughness: 5,
			role: "Fast Attack",
			weapons: ["bolt-pistol", "chainsword"],
			invulnSave: null,
		},
		{
			name: "Eradicators",
			wounds: 3,
			models: 3,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 5,
			toughness: 5,
			role: "Heavy Support",
			weapons: ["melta-rifle", "bolt-pistol"],
			invulnSave: null,
		},
		{
			name: "Hellblasters",
			wounds: 2,
			models: 5,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Fire Support",
			weapons: ["plasma-incinerator", "bolt-pistol"],
			invulnSave: null,
		},
		{
			name: "Devastator Squad",
			wounds: 1,
			models: 5,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Heavy Support",
			weapons: ["boltgun", "bolt-pistol"],
			invulnSave: null,
		},
		{
			name: "Suppressors",
			wounds: 2,
			models: 3,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 12,
			toughness: 4,
			role: "Heavy Support",
			weapons: ["bolt-pistol"],
			invulnSave: null,
		},
		{
			name: "Centurion Devastators",
			wounds: 4,
			models: 3,
			save: 2,
			leadership: 6,
			oc: 1,
			movement: 5,
			toughness: 5,
			role: "Heavy Support",
			weapons: ["bolt-pistol"],
			invulnSave: null,
		},
		{
			name: "Invictor Tactical Warsuit",
			wounds: 13,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 3,
			movement: 10,
			toughness: 7,
			role: "Vehicle",
			weapons: ["heavy-bolter", "storm-bolter"],
			invulnSave: null,
		},
	],
	"imperial-guard": [
		{
			name: "Infantry Squad",
			wounds: 1,
			models: 10,
			save: 5,
			leadership: 7,
			oc: 2,
			movement: 6,
			toughness: 3,
			role: "Battleline",
			weapons: ["lasgun", "laspistol"],
			invulnSave: null,
		},
		{
			name: "Cadian Shock Troops",
			wounds: 1,
			models: 10,
			save: 5,
			leadership: 7,
			oc: 2,
			movement: 6,
			toughness: 3,
			role: "Battleline",
			weapons: ["lasgun", "laspistol"],
			invulnSave: null,
		},
		{
			name: "Tempestus Scions",
			wounds: 1,
			models: 5,
			save: 4,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Battleline",
			weapons: ["hot-shot-lasgun", "plasma-gun"],
			invulnSave: null,
		},
		{
			name: "Kasrkin",
			wounds: 1,
			models: 10,
			save: 4,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Elite",
			weapons: ["hot-shot-lasgun", "plasma-gun", "meltagun"],
			invulnSave: null,
		},
		{
			name: "Command Squad",
			wounds: 2,
			models: 5,
			save: 5,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Character",
			weapons: ["laspistol", "plasma-gun"],
			invulnSave: null,
		},
		{
			name: "Commissar",
			wounds: 3,
			models: 1,
			save: 5,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Character",
			weapons: ["bolt-pistol", "power-sword"],
			invulnSave: null,
		},
		{
			name: "Ogryns",
			wounds: 3,
			models: 3,
			save: 5,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 6,
			role: "Elite",
			weapons: ["ripper-gun"],
			invulnSave: null,
		},
		{
			name: "Bullgryns",
			wounds: 3,
			models: 3,
			save: 4,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 6,
			role: "Elite",
			weapons: ["ripper-gun"],
			invulnSave: null,
		},
		{
			name: "Ratlings",
			wounds: 1,
			models: 5,
			save: 5,
			leadership: 7,
			oc: 1,
			movement: 5,
			toughness: 2,
			role: "Elite",
			weapons: ["lasgun"],
			invulnSave: null,
		},
		{
			name: "Sentinel",
			wounds: 6,
			models: 1,
			save: 4,
			leadership: 7,
			oc: 2,
			movement: 10,
			toughness: 6,
			role: "Fast Attack",
			weapons: ["multi-laser", "plasma-gun"],
			invulnSave: null,
		},
		{
			name: "Scout Sentinel",
			wounds: 6,
			models: 1,
			save: 4,
			leadership: 7,
			oc: 2,
			movement: 12,
			toughness: 6,
			role: "Fast Attack",
			weapons: ["multi-laser"],
			invulnSave: null,
		},
		{
			name: "Armoured Sentinel",
			wounds: 6,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 2,
			movement: 9,
			toughness: 6,
			role: "Fast Attack",
			weapons: ["multi-laser"],
			invulnSave: null,
		},
		{
			name: "Leman Russ Battle Tank",
			wounds: 13,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 3,
			movement: 10,
			toughness: 10,
			role: "Vehicle",
			weapons: ["battle-cannon", "laspistol"],
			invulnSave: null,
		},
		{
			name: "Baneblade",
			wounds: 30,
			models: 1,
			save: 2,
			leadership: 8,
			oc: 10,
			movement: 10,
			toughness: 14,
			role: "Vehicle",
			weapons: ["battle-cannon"],
			invulnSave: null,
		},
		{
			name: "Chimera",
			wounds: 10,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 2,
			movement: 12,
			toughness: 9,
			role: "Vehicle",
			weapons: ["multi-laser"],
			invulnSave: null,
		},
		{
			name: "Hellhound",
			wounds: 11,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 2,
			movement: 12,
			toughness: 9,
			role: "Vehicle",
			weapons: ["flamer"],
			invulnSave: null,
		},
		{
			name: "Basilisk",
			wounds: 11,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 2,
			movement: 12,
			toughness: 9,
			role: "Vehicle",
			weapons: ["battle-cannon"],
			invulnSave: null,
		},
		{
			name: "Hydra",
			wounds: 11,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 2,
			movement: 12,
			toughness: 9,
			role: "Vehicle",
			weapons: ["multi-laser"],
			invulnSave: null,
		},
	],
	sisters: [
		{
			name: "Battle Sisters Squad",
			wounds: 1,
			models: 10,
			save: 3,
			leadership: 7,
			oc: 2,
			movement: 6,
			toughness: 3,
			role: "Battleline",
			weapons: ["bolter", "storm-bolter-sororitas", "flamer"],
			invulnSave: 6,
		},
		{
			name: "Celestian Squad",
			wounds: 1,
			models: 5,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Elite",
			weapons: ["bolter", "flamer"],
			invulnSave: 6,
		},
		{
			name: "Repentia Squad",
			wounds: 1,
			models: 5,
			save: 6,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Elite",
			weapons: ["chainsword"],
			invulnSave: 5,
		},
		{
			name: "Dominion Squad",
			wounds: 1,
			models: 5,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Fast Attack",
			weapons: ["bolter", "flamer"],
			invulnSave: 6,
		},
		{
			name: "Retributor Squad",
			wounds: 1,
			models: 5,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Heavy Support",
			weapons: ["bolter"],
			invulnSave: 6,
		},
		{
			name: "Seraphim Squad",
			wounds: 1,
			models: 5,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 12,
			toughness: 3,
			role: "Fast Attack",
			weapons: ["bolt-pistol"],
			invulnSave: 6,
		},
		{
			name: "Zephyrim Squad",
			wounds: 1,
			models: 5,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 12,
			toughness: 3,
			role: "Fast Attack",
			weapons: ["bolt-pistol"],
			invulnSave: 6,
		},
		{
			name: "Arco-Flagellants",
			wounds: 1,
			models: 5,
			save: 7,
			leadership: 7,
			oc: 1,
			movement: 7,
			toughness: 3,
			role: "Elite",
			weapons: ["chainsword"],
			invulnSave: 5,
		},
		{
			name: "Penitent Engines",
			wounds: 7,
			models: 1,
			save: 4,
			leadership: 7,
			oc: 2,
			movement: 8,
			toughness: 6,
			role: "Elite",
			weapons: ["chainsword"],
			invulnSave: 5,
		},
		{
			name: "Canoness",
			wounds: 4,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Character",
			weapons: ["bolter", "chainsword"],
			invulnSave: 4,
		},
		{
			name: "Palatine",
			wounds: 4,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Character",
			weapons: ["bolter"],
			invulnSave: 4,
		},
		{
			name: "Dialogus",
			wounds: 4,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Character",
			weapons: ["bolter"],
			invulnSave: 4,
		},
		{
			name: "Hospitaller",
			wounds: 4,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Character",
			weapons: ["bolter"],
			invulnSave: 4,
		},
		{
			name: "Imagifier",
			wounds: 4,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Character",
			weapons: ["bolter"],
			invulnSave: 4,
		},
		{
			name: "Missionary",
			wounds: 4,
			models: 1,
			save: 5,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Character",
			weapons: ["bolter"],
			invulnSave: 4,
		},
		{
			name: "Sister Superior",
			wounds: 1,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Character",
			weapons: ["bolter"],
			invulnSave: 6,
		},
	],
	custodes: [
		{
			name: "Custodian Guard",
			wounds: 3,
			models: 3,
			save: 2,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 5,
			role: "Battleline",
			weapons: ["guardian-spear", "sentinel-blade"],
			invulnSave: 4,
		},
		// ...add all other Adeptus Custodes units...
	],
	"chaos-marines": [
		{
			name: "Chaos Space Marines",
			wounds: 1,
			models: 10,
			save: 3,
			leadership: 7,
			oc: 2,
			movement: 6,
			toughness: 4,
			role: "Battleline",
			weapons: ["chaos-boltgun", "chainsword"],
			invulnSave: null,
		},
		{
			name: "Chosen",
			wounds: 2,
			models: 5,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Elite",
			weapons: ["chaos-boltgun", "chainsword"],
			invulnSave: null,
		},
		{
			name: "Havocs",
			wounds: 2,
			models: 5,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 5,
			role: "Heavy Support",
			weapons: ["chaos-boltgun"],
			invulnSave: null,
		},
		{
			name: "Cultists",
			wounds: 1,
			models: 10,
			save: 6,
			leadership: 7,
			oc: 2,
			movement: 6,
			toughness: 3,
			role: "Battleline",
			weapons: ["autopistol", "cultist-knife"],
			invulnSave: null,
		},
		{
			name: "Dark Apostle",
			wounds: 5,
			models: 1,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Character",
			weapons: ["chaos-boltgun", "chainsword"],
			invulnSave: 4,
		},
		{
			name: "Exalted Champion",
			wounds: 5,
			models: 1,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Character",
			weapons: ["chaos-boltgun", "chainsword"],
			invulnSave: 4,
		},
		{
			name: "Chaos Lord",
			wounds: 5,
			models: 1,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Character",
			weapons: ["chaos-boltgun", "chainsword"],
			invulnSave: 4,
		},
		{
			name: "Sorcerer",
			wounds: 5,
			models: 1,
			save: 3,
			leadership: 6,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Character",
			weapons: ["chaos-boltgun"],
			invulnSave: 5,
		},
		{
			name: "Helbrute",
			wounds: 9,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 3,
			movement: 8,
			toughness: 7,
			role: "Vehicle",
			weapons: ["chaos-boltgun"],
			invulnSave: null,
		},
		{
			name: "Obliterators",
			wounds: 4,
			models: 3,
			save: 2,
			leadership: 7,
			oc: 1,
			movement: 5,
			toughness: 5,
			role: "Heavy Support",
			weapons: ["chaos-boltgun"],
			invulnSave: 5,
		},
		{
			name: "Warp Talons",
			wounds: 2,
			models: 5,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 12,
			toughness: 4,
			role: "Fast Attack",
			weapons: ["chaos-boltgun"],
			invulnSave: 5,
		},
		{
			name: "Raptors",
			wounds: 1,
			models: 5,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 12,
			toughness: 4,
			role: "Fast Attack",
			weapons: ["chaos-boltgun"],
			invulnSave: null,
		},
	],
	"death-guard": [
		{
			name: "Plague Marines",
			wounds: 2,
			models: 5,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 5,
			toughness: 5,
			role: "Battleline",
			weapons: ["plague-bolter", "plague-knife"],
			invulnSave: null,
		},
		// ...add all other Death Guard units...
	],
	"thousand-sons": [
		{
			name: "Rubric Marines",
			wounds: 2,
			models: 5,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 4,
			role: "Battleline",
			weapons: ["inferno-boltgun", "force-stave"],
			invulnSave: 5,
		},
		// ...add all other Thousand Sons units...
	],
	orks: [
		{
			name: "Boyz",
			wounds: 1,
			models: 10,
			save: 6,
			leadership: 7,
			oc: 2,
			movement: 6,
			toughness: 5,
			role: "Battleline",
			weapons: ["shoota", "slugga", "choppa"],
			invulnSave: null,
		},
		{
			name: "Warboss",
			wounds: 6,
			models: 1,
			save: 4,
			leadership: 6,
			oc: 1,
			movement: 5,
			toughness: 6,
			role: "Character",
			weapons: ["slugga", "choppa"],
			invulnSave: 4,
		},
		// ...add all other Ork units...
	],
	tau: [
		{
			name: "Fire Warriors",
			wounds: 1,
			models: 10,
			save: 4,
			leadership: 7,
			oc: 2,
			movement: 6,
			toughness: 3,
			role: "Battleline",
			weapons: ["pulse-rifle", "pulse-carbine"],
			invulnSave: null,
		},
		{
			name: "Crisis Battlesuit",
			wounds: 4,
			models: 3,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 10,
			toughness: 5,
			role: "Elite",
			weapons: ["fusion-blaster", "pulse-carbine"],
			invulnSave: null,
		},
		// ...add all other Tau units...
	],
	necrons: [
		{
			name: "Necron Warriors",
			wounds: 1,
			models: 10,
			save: 4,
			leadership: 10,
			oc: 2,
			movement: 5,
			toughness: 4,
			role: "Battleline",
			weapons: ["gauss-flayer", "gauss-reaper"],
			invulnSave: null,
			abilities: ["Reanimation Protocols"],
		},
		{
			name: "Lychguard",
			wounds: 2,
			models: 5,
			save: 3,
			leadership: 9,
			oc: 1,
			movement: 5,
			toughness: 5,
			role: "Elite",
			weapons: ["hyperphase-sword"],
			invulnSave: 4,
			abilities: ["Reanimation Protocols"],
		},
		// ...add all other Necron units...
	],
	eldar: [
		{
			name: "Guardian Defenders",
			wounds: 1,
			models: 10,
			save: 5,
			leadership: 7,
			oc: 2,
			movement: 7,
			toughness: 3,
			role: "Battleline",
			weapons: ["shuriken-catapult"],
			invulnSave: null,
		},
		{
			name: "Dire Avengers",
			wounds: 1,
			models: 5,
			save: 4,
			leadership: 7,
			oc: 1,
			movement: 7,
			toughness: 3,
			role: "Battleline",
			weapons: ["shuriken-catapult", "shuriken-pistol"],
			invulnSave: null,
		},
		// ...add all other Aeldari units...
	],
	drukhari: [
		{
			name: "Kabalite Warriors",
			wounds: 1,
			models: 10,
			save: 5,
			leadership: 7,
			oc: 2,
			movement: 7,
			toughness: 3,
			role: "Battleline",
			weapons: ["splinter-rifle"],
			invulnSave: null,
		},
		{
			name: "Wyches",
			wounds: 1,
			models: 10,
			save: 6,
			leadership: 7,
			oc: 2,
			movement: 8,
			toughness: 3,
			role: "Battleline",
			weapons: ["agoniser"],
			invulnSave: null,
		},
		// ...add all other Drukhari units...
	],
	tyranids: [
		{
			name: "Termagants",
			wounds: 1,
			models: 10,
			save: 5,
			leadership: 8,
			oc: 2,
			movement: 6,
			toughness: 3,
			role: "Battleline",
			weapons: ["fleshborer"],
			invulnSave: null,
		},
		{
			name: "Hormagaunts",
			wounds: 1,
			models: 10,
			save: 6,
			leadership: 8,
			oc: 2,
			movement: 10,
			toughness: 3,
			role: "Battleline",
			weapons: ["scything-talons"],
			invulnSave: null,
		},
		{
			name: "Genestealers",
			wounds: 1,
			models: 10,
			save: 5,
			leadership: 7,
			oc: 1,
			movement: 8,
			toughness: 4,
			role: "Battleline",
			weapons: ["rending-claws"],
			invulnSave: 5,
		},
		{
			name: "Warriors",
			wounds: 3,
			models: 3,
			save: 4,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 5,
			role: "Elite",
			weapons: ["devourer", "scything-talons"],
			invulnSave: null,
		},
		{
			name: "Hive Tyrant",
			wounds: 10,
			models: 1,
			save: 3,
			leadership: 8,
			oc: 1,
			movement: 9,
			toughness: 9,
			role: "Character",
			weapons: ["venom-cannon", "monstrous-bonesword"],
			invulnSave: 4,
		},
		{
			name: "Carnifex",
			wounds: 9,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 7,
			toughness: 9,
			role: "Monster",
			weapons: ["devourer", "monstrous-scything-talons"],
			invulnSave: null,
		},
		{
			name: "Hive Guard",
			wounds: 3,
			models: 3,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 5,
			toughness: 6,
			role: "Heavy Support",
			weapons: ["impaler-cannon"],
			invulnSave: null,
		},
		{
			name: "Zoanthropes",
			wounds: 4,
			models: 3,
			save: 4,
			leadership: 8,
			oc: 1,
			movement: 6,
			toughness: 5,
			role: "Psyker",
			weapons: ["warp-blast"],
			invulnSave: 4,
		},
		{
			name: "Tyrant Guard",
			wounds: 3,
			models: 3,
			save: 3,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 6,
			role: "Elite",
			weapons: ["scything-talons"],
			invulnSave: null,
		},
		{
			name: "Raveners",
			wounds: 3,
			models: 3,
			save: 4,
			leadership: 7,
			oc: 1,
			movement: 12,
			toughness: 5,
			role: "Fast Attack",
			weapons: ["scything-talons"],
			invulnSave: null,
		},
		{
			name: "Trygon",
			wounds: 14,
			models: 1,
			save: 3,
			leadership: 8,
			oc: 3,
			movement: 12,
			toughness: 8,
			role: "Monster",
			weapons: ["scything-talons"],
			invulnSave: null,
		},
		{
			name: "Mawloc",
			wounds: 14,
			models: 1,
			save: 3,
			leadership: 8,
			oc: 3,
			movement: 12,
			toughness: 8,
			role: "Monster",
			weapons: ["scything-talons"],
			invulnSave: null,
		},
		{
			name: "Tervigon",
			wounds: 16,
			models: 1,
			save: 3,
			leadership: 8,
			oc: 5,
			movement: 8,
			toughness: 10,
			role: "Monster",
			weapons: ["scything-talons"],
			invulnSave: null,
		},
		{
			name: "Exocrine",
			wounds: 12,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 3,
			movement: 6,
			toughness: 9,
			role: "Heavy Support",
			weapons: ["venom-cannon"],
			invulnSave: null,
		},
		{
			name: "Biovores",
			wounds: 4,
			models: 3,
			save: 4,
			leadership: 7,
			oc: 1,
			movement: 5,
			toughness: 5,
			role: "Heavy Support",
			weapons: ["venom-cannon"],
			invulnSave: null,
		},
		{
			name: "Pyrovores",
			wounds: 3,
			models: 3,
			save: 4,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 5,
			role: "Elite",
			weapons: ["flamer"],
			invulnSave: null,
		},
		{
			name: "Sporocyst",
			wounds: 10,
			models: 1,
			save: 3,
			leadership: 7,
			oc: 2,
			movement: 0,
			toughness: 8,
			role: "Fortification",
			weapons: ["venom-cannon"],
			invulnSave: null,
		},
		{
			name: "Harpy",
			wounds: 12,
			models: 1,
			save: 3,
			leadership: 8,
			oc: 3,
			movement: 16,
			toughness: 8,
			role: "Flyer",
			weapons: ["venom-cannon"],
			invulnSave: null,
		},
		{
			name: "Hive Crone",
			wounds: 12,
			models: 1,
			save: 3,
			leadership: 8,
			oc: 3,
			movement: 16,
			toughness: 8,
			role: "Flyer",
			weapons: ["venom-cannon"],
			invulnSave: null,
		},
	],
	genestealer: [
		{
			name: "Neophyte Hybrids",
			wounds: 1,
			models: 10,
			save: 5,
			leadership: 7,
			oc: 2,
			movement: 6,
			toughness: 3,
			role: "Battleline",
			weapons: ["autopistol", "cultist-knife"],
			invulnSave: null,
		},
		{
			name: "Acolyte Hybrids",
			wounds: 1,
			models: 5,
			save: 5,
			leadership: 7,
			oc: 1,
			movement: 6,
			toughness: 3,
			role: "Battleline",
			weapons: ["autopistol", "cultist-knife"],
			invulnSave: null,
		},
		// ...add all other Genestealer Cults units...
	],
	// Add more factions and units as needed
};

// Abilities database (sample, expand as needed)
const abilitiesDatabase = {
	"Rapid Fire 1": "Double attacks if target is within half range.",
	Pistol: "Can shoot even if engaged.",
	Blast: "Add 1 attack for every 5 models in the target unit.",
	Assault: "Can advance and shoot.",
	"Plague Weapon": "Re-roll wound rolls of 1.",
	"Reanimation Protocols":
		"Roll a D6 for each destroyed model in your Command phase. On a 5+, return one model.",
	Shuriken: "AP improves to -3 on wound rolls of 6.",
	Poisoned: "Always wounds on a 4+ unless better.",
	"Extra Attack": "Grants an additional attack.",
	Psychic: "Can manifest psychic powers.",
	"Dakka! Dakka!": "Unmodified hit rolls of 6 score an additional hit.",
	"Melta 2": "If within half range, add 2 to damage.",
	"Lethal Hits": "Critical hits automatically wound.",
	// ...add all other abilities...
	"Rapid Fire 2": "Double attacks if target is within half range (2 steps).",
	"Sustained Hits 1": "Critical hit scores 1 additional hit.",
	"Auto Hits":
		"This weapon automatically hits its target; do not make hit rolls.",
	Hazardous:
		"If any Hit roll is 1, the bearer suffers mortal wounds per rules.",
	Rending: "Improve AP by -1 (or as profile) on Critical Wounds.",
	"Re-roll Hit rolls of 1": "When attacking, re-roll hit rolls of 1.",
	"-1 to Hit": "Attacks with this weapon suffer -1 to the Hit roll.",
};

// Minimal stratagem/command database used by helper-10 UI
const factionCommands = {
	"space-marines": [
		{
			key: "oath-of-moment",
			name: "Oath of Moment",
			description:
				"Select one enemy unit until end of turn: attacks from your army can re-roll Hits against that unit.",
			phase: "command",
			cost: 1,
			target: "enemy",
			type: "strategic",
			expires: "end-of-turn",
		},
		{
			key: "transhuman",
			name: "Transhuman Physiology",
			description:
				"Select one friendly unit until end of turn: it cannot be wounded on a roll of 1–3 (only 4+ or better).",
			phase: "command",
			cost: 1,
			target: "friendly",
			type: "defensive",
			expires: "end-of-turn",
		},
		{
			key: "armor-of-contempt",
			name: "Armour of Contempt",
			description:
				"Select one friendly unit until end of turn: worsen AP of incoming attacks by 1.",
			phase: "command",
			cost: 1,
			target: "friendly",
			type: "defensive",
			expires: "end-of-turn",
		},
	],
	"imperial-guard": [
		{
			key: "take-cover",
			name: "Take Cover!",
			description:
				"Select a friendly Infantry unit; improve its Save against ranged attacks by 1 until end of turn.",
			phase: "command",
			cost: 1,
			target: "friendly",
			type: "defensive",
			expires: "end-of-turn",
		},
		{
			key: "overlapping-fields",
			name: "Overlapping Fields of Fire",
			description:
				"Select an enemy unit; until end of turn, friendly units get +1 to Hit when targeting it.",
			phase: "command",
			cost: 1,
			target: "enemy",
			type: "strategic",
			expires: "end-of-turn",
		},
	],
	sisters: [
		{
			key: "faith-shield",
			name: "Shield of Faith",
			description:
				"Select a friendly unit; improve invulnerable save by 1 this turn.",
			phase: "command",
			cost: 1,
			target: "friendly",
			type: "defensive",
			expires: "end-of-turn",
		},
	],
	"chaos-marines": [
		{
			key: "dark-pact",
			name: "Dark Pact",
			description:
				"Select a friendly unit; improve AP by 1 on melee attacks this turn (may take mortals on 1s).",
			phase: "command",
			cost: 1,
			target: "friendly",
			type: "offensive",
			expires: "end-of-turn",
		},
	],
	orks: [
		{
			key: "more-dakka",
			name: "More Dakka!",
			description:
				"Select a friendly unit; grant Sustained Hits 1 on ranged attacks this turn.",
			phase: "command",
			cost: 1,
			target: "friendly",
			type: "offensive",
			expires: "end-of-turn",
		},
	],
	tyranids: [
		{
			key: "synaptic-impulse",
			name: "Synaptic Impulse",
			description:
				"Select a friendly unit; it can re-roll Battle-shock tests this turn.",
			phase: "command",
			cost: 0,
			target: "friendly",
			type: "utility",
			expires: "end-of-turn",
		},
	],
};

// --- Normalise common faction identifiers so UI lookups are resilient ---
const FACTION_ALIASES = {
	"adepta-sororitas": "sisters",
	"astra-militarum": "imperial-guard",
	"imperial guard": "imperial-guard",
	"chaos space marines": "chaos-marines",
	"chaos-space-marines": "chaos-marines",
	aeldari: "eldar",
	asuryani: "eldar",
	"druk-hari": "drukhari",
	"genestealer-cults": "genestealer",
	"genestealer cults": "genestealer",
	"t'au": "tau",
	"tau empire": "tau",
};
Object.entries(FACTION_ALIASES).forEach(([alias, canonical]) => {
	if (unitDatabase[canonical] && !unitDatabase[alias]) {
		unitDatabase[alias] = unitDatabase[canonical];
	}
	if (
		typeof factionCommands !== "undefined" &&
		factionCommands[canonical] &&
		!factionCommands[alias]
	) {
		factionCommands[alias] = factionCommands[canonical];
	}
});
// Export for use in main app
if (typeof window !== "undefined") {
	window.weaponProfiles = weaponProfiles;
	window.unitDatabase = unitDatabase;
	window.abilitiesDatabase = abilitiesDatabase;
	window.factionCommands = factionCommands;
}
